//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vbfextract.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("vbfextract.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ffx_data/gamedata/ps3data/yonishi_data/dat_et/et_ffx/tex/texlist.txt
        ///ffx_data/gamedata/ps3data/yonishi_data/dat_et/et_ffx/tex/d3d11/15040_19_0_0_128_128.dds.phyre
        ///ffx_data/gamedata/ps3data/yonishi_data/dat_et/bat_eff/et_tex/tex/texlist.txt
        ///ffx_data/gamedata/ps3data/yonishi_data/dat_et/bat_eff/et_tex/tex/d3d11/15392_19_0_0_128_64.dds.phyre
        ///ffx_data/gamedata/ps3data/yonishi_data/dat_et/bat_eff/et_tex/tex/d3d11/15424_19_0_0_128_64.dds.phyre
        ///ffx_data/gamedata/ps3data/yonishi_data/dat_et/bat_eff/et_tex/tex/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FFX_Data_1 {
            get {
                return ResourceManager.GetString("FFX_Data_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ffx-2_data/gamedata/ps3data/yonishi_data/dat_et/et_ffx/tex/texlist.txt
        ///ffx-2_data/gamedata/ps3data/yonishi_data/dat_et/et_ffx/tex/d3d11/15040_19_0_0_128_128.dds.phyre
        ///ffx-2_data/gamedata/ps3data/yonishi_data/dat_et/bat_eff/et_tex/tex/texlist.txt
        ///ffx-2_data/gamedata/ps3data/yonishi_data/dat_et/bat_eff/et_tex/tex/d3d11/15392_19_0_0_128_64.dds.phyre
        ///ffx-2_data/gamedata/ps3data/yonishi_data/dat_et/bat_eff/et_tex/tex/d3d11/15424_19_0_0_128_64.dds.phyre
        ///ffx-2_data/gamedata/ps3data/yonishi_data/dat_et/bat_eff [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FFX2_Data_1 {
            get {
                return ResourceManager.GetString("FFX2_Data_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to metamenu/ps3data/menucredit/button_down.png
        ///metamenu/ps3data/menucredit/button_over.png
        ///metamenu/ps3data/menucredit/button_up.png
        ///metamenu/ps3data/menucredit/credits_1280.png
        ///metamenu/ps3data/menucredit/scollbar.png
        ///metamenu/ps3data/menucredit/us/credits_logo.png
        ///metamenu/ps3data/menucredit/sp/credits_logo.png
        ///metamenu/ps3data/menucredit/kr/credits_logo.png
        ///metamenu/ps3data/menucredit/jp/credits_logo.png
        ///metamenu/ps3data/menucredit/it/credits_logo.png
        ///metamenu/ps3data/menucredit/fr/credits_logo.png
        ///metamenu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string metamenu_1 {
            get {
                return ResourceManager.GetString("metamenu_1", resourceCulture);
            }
        }
    }
}
